//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digiDownloadPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NationCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NationCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("digiDownloadPC.Properties.NationCodes", typeof(NationCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string NATION_0 {
            get {
                return ResourceManager.GetString("NATION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string NATION_A {
            get {
                return ResourceManager.GetString("NATION_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string NATION_AL {
            get {
                return ResourceManager.GetString("NATION_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        internal static string NATION_AND {
            get {
                return ResourceManager.GetString("NATION_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string NATION_ARM {
            get {
                return ResourceManager.GetString("NATION_ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string NATION_AZ {
            get {
                return ResourceManager.GetString("NATION_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string NATION_B {
            get {
                return ResourceManager.GetString("NATION_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string NATION_BG {
            get {
                return ResourceManager.GetString("NATION_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia Herzegovina.
        /// </summary>
        internal static string NATION_BIH {
            get {
                return ResourceManager.GetString("NATION_BIH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string NATION_BY {
            get {
                return ResourceManager.GetString("NATION_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string NATION_CH {
            get {
                return ResourceManager.GetString("NATION_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        internal static string NATION_CY {
            get {
                return ResourceManager.GetString("NATION_CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string NATION_CZ {
            get {
                return ResourceManager.GetString("NATION_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string NATION_D {
            get {
                return ResourceManager.GetString("NATION_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string NATION_DK {
            get {
                return ResourceManager.GetString("NATION_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string NATION_E {
            get {
                return ResourceManager.GetString("NATION_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Community.
        /// </summary>
        internal static string NATION_EC {
            get {
                return ResourceManager.GetString("NATION_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string NATION_EST {
            get {
                return ResourceManager.GetString("NATION_EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest of Europe.
        /// </summary>
        internal static string NATION_EUR {
            get {
                return ResourceManager.GetString("NATION_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string NATION_F {
            get {
                return ResourceManager.GetString("NATION_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string NATION_FIN {
            get {
                return ResourceManager.GetString("NATION_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string NATION_FL {
            get {
                return ResourceManager.GetString("NATION_FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        internal static string NATION_FO {
            get {
                return ResourceManager.GetString("NATION_FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string NATION_GE {
            get {
                return ResourceManager.GetString("NATION_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string NATION_GR {
            get {
                return ResourceManager.GetString("NATION_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        internal static string NATION_H {
            get {
                return ResourceManager.GetString("NATION_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string NATION_HR {
            get {
                return ResourceManager.GetString("NATION_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string NATION_I {
            get {
                return ResourceManager.GetString("NATION_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string NATION_IRL {
            get {
                return ResourceManager.GetString("NATION_IRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string NATION_IS {
            get {
                return ResourceManager.GetString("NATION_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string NATION_KZ {
            get {
                return ResourceManager.GetString("NATION_KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string NATION_L {
            get {
                return ResourceManager.GetString("NATION_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string NATION_LT {
            get {
                return ResourceManager.GetString("NATION_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string NATION_LV {
            get {
                return ResourceManager.GetString("NATION_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string NATION_M {
            get {
                return ResourceManager.GetString("NATION_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string NATION_MC {
            get {
                return ResourceManager.GetString("NATION_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova.
        /// </summary>
        internal static string NATION_MD {
            get {
                return ResourceManager.GetString("NATION_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Macedonia.
        /// </summary>
        internal static string NATION_MK {
            get {
                return ResourceManager.GetString("NATION_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string NATION_MNE {
            get {
                return ResourceManager.GetString("NATION_MNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string NATION_N {
            get {
                return ResourceManager.GetString("NATION_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string NATION_NL {
            get {
                return ResourceManager.GetString("NATION_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string NATION_P {
            get {
                return ResourceManager.GetString("NATION_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string NATION_PL {
            get {
                return ResourceManager.GetString("NATION_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string NATION_RO {
            get {
                return ResourceManager.GetString("NATION_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        internal static string NATION_RSM {
            get {
                return ResourceManager.GetString("NATION_RSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string NATION_RUS {
            get {
                return ResourceManager.GetString("NATION_RUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string NATION_S {
            get {
                return ResourceManager.GetString("NATION_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string NATION_SK {
            get {
                return ResourceManager.GetString("NATION_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string NATION_SLO {
            get {
                return ResourceManager.GetString("NATION_SLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string NATION_SRB {
            get {
                return ResourceManager.GetString("NATION_SRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string NATION_TJ {
            get {
                return ResourceManager.GetString("NATION_TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string NATION_TM {
            get {
                return ResourceManager.GetString("NATION_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string NATION_TR {
            get {
                return ResourceManager.GetString("NATION_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string NATION_UA {
            get {
                return ResourceManager.GetString("NATION_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string NATION_UK {
            get {
                return ResourceManager.GetString("NATION_UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string NATION_UZ {
            get {
                return ResourceManager.GetString("NATION_UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatican City.
        /// </summary>
        internal static string NATION_V {
            get {
                return ResourceManager.GetString("NATION_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest of World.
        /// </summary>
        internal static string NATION_WLD {
            get {
                return ResourceManager.GetString("NATION_WLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yugoslavia.
        /// </summary>
        internal static string NATION_YU {
            get {
                return ResourceManager.GetString("NATION_YU", resourceCulture);
            }
        }
    }
}
